### ISSUE TITLE
Phase retrieval convergence with test PSF data

### ISSUE THREAD

**Issue by nvladimus** [david-hoffman/pyOTF#15]
Hi, @david-hoffman,
pyOTF is very cool library, thanks for developing it! I am trying to learn it, in order to compute phase aberrations from experimental PSF. I tried to run it on  experimental PSF you have in `/fixtures/psf_wl520nm_z300nm_x130nm_na0.85_n1.0.tif` , but the MSE plots look weird, it does not seem to converge nicely. 
Here is what I run:
```
%pylab inline
from pyotf.phaseretrieval import retrieve_phase
import pyotf.utils as utils
import tifffile as tif

test_data = tif.imread("./psf/psf_wl520nm_z300nm_x130nm_na0.85_n1.0.tif")
params = dict(size = test_data.shape[-1],  zsize = test_data.shape[0],
    na = 0.85, res = 130,  zres = 300,  wl = 520,   ni = 1.0,
    vec_corr="none",  condition="none"
)

PR_result = retrieve_phase(utils.prep_data_for_PR(test_data), params, max_iters=100, pupil_tol=0, mse_tol=0, phase_only=True)
PR_result.plot()
PR_result.plot_convergence()
```

And here is what the plots look like:
![image](https://user-images.githubusercontent.com/10835134/106775365-5764d500-6643-11eb-9661-fea8b500843a.png)
![image](https://user-images.githubusercontent.com/10835134/106775420-6481c400-6643-11eb-8ce5-a608f1da8318.png)

Can you give some hints what I am doing incorrectly? 

Thank you!

**Comment by david-hoffman** [comment]
That looks fine to me, it’s the way the algorithm works. There’s no guarantee that the MSE will decrease just that the pupil estimate will converge, which it is.

**Comment by nvladimus** [comment]
OK, thanks! So, the sign that algorithm works is pupil estimate going down? How do I know the algorithm didn't work correctly?

**Comment by david-hoffman** [comment]
It’s like deconvolution: there’s no algorithmic way to tell that it didn’t work. 

I generally analyze a bunch of PSFs and take the median for each zernike mode.

**Comment by nvladimus** [comment]
Thanks!

**Comment by nvladimus** [comment]
Sorry, I am still confused: MSE seems to be calculated between experimental PSF and model PSF, so shouldn't it go down if the algorithm works? Hanser et al also measure their algorithm success in MSE...

**Comment by nvladimus** [comment]
I am trying on my experimental PSF, and the plots look simply blank. I guess I am doing something stupid, but I can't figure what...
```
prepped_data = utils.prep_data_for_PR(psf_data, xysize=32)
params = dict(na = 0.8, res = 146, zres = 707, wl = 520, ni = 1.33)
PR_result = retrieve_phase(prepped_data, params, phase_only=True)
```
![image](https://user-images.githubusercontent.com/10835134/107030748-5ce02d80-67b1-11eb-8550-f8f2285277e9.png)
![image](https://user-images.githubusercontent.com/10835134/107031259-2ce55a00-67b2-11eb-9cbc-13331414aacc.png)

**Comment by david-hoffman** [comment]
Sorry I didn't see an issue earlier:

`PR_result = retrieve_phase(prepped_data, params, phase_only=True)`

Should be 

`PR_result = retrieve_phase(prepped_data, params, phase_only=False)`

That's why the MSE plot above looks weird.

For your latest question, the problem is that the change in the MSE is below the set tolerance (`1e-8`) and so the algorithm only runs for 1 iteration. If you want to force it to run for longer than you can set `mse_tol` to `0`.

I'd also recommend using more pixels if possible.

Finally, try playing around with the `multiplier` key word for the `prep_data_for_PR` function. The closer you can get to `1` without introducing too much noise the better.

**Comment by nvladimus** [comment]
Thank you!

**Comment by david-hoffman** [comment]
@nvladimus I just realized, the algorithm only guarantees convergence of the _estimated pupil function_. MSE of between the real and predicted intensity PSF is not guaranteed to converge.
