### ISSUE TITLE
generate radial zernike from jacobi polynomial

### ISSUE THREAD

**Issue by SILI1994** [david-hoffman/pyOTF#22]
Hi, thank you for the nice code.

I have a question w.r.t. the code [here](https://github.com/david-hoffman/pyOTF/blob/7fb39dbc9559cde24124792b209415c338b4fe8b/pyotf/zernike.py#L298). Shouldn't the exponential of `-1` be `(m-n) // 2` instead of `(m+n) // 2`?  I am referring to the equation~8 in [this tutorial](https://archive.lib.msu.edu/crcmath/math/math/z/z027.htm).

**Comment by david-hoffman** [comment]
I think you're right. This changes the signs of some of the polynomials, but all of the tests are passing so hopefully it's not a breaking change.

Good catch

**Comment by SILI1994** [comment]
Interestingly, [Wolfram](https://mathworld.wolfram.com/ZernikePolynomial.html) gives a third exponential coefficient. I guess these signs are not important as long as the bases are pairwise orthogonal. They may just like the left-hand and right-hand coordinates in the 3D cartesian coordinate.

**Comment by david-hoffman** [comment]
It looks like equation (6) on the Wolfram link is identical to equation (8) in your original post. Am I missing something?

**Comment by SILI1994** [comment]
Ah yeah, they are of the same sign. Sorry my fault
