### ISSUE TITLE
Add code to simulate actual microscopes

### ISSUE THREAD

**Issue by david-hoffman** [david-hoffman/pyOTF#7]
The code as it currently is only simulates the wavefront a the camera in a widefield/epi scope, but with a few modifications multiple different microscope PSFs (and OTFs) can be modeled. The following should be doable

- [x] Epi
- [x] Confocal
- [x] Apotome (approximation of non-linear function, i.e. no real OTF for this reconstruction method)
- [x] SIM (of all varieties)
  - [x] OS-SIM
  - [x] 2D-SIM
  - [x] 3D-SIM & (Zeiss Lattice SIM)

**Comment by david-hoffman** [comment]
![Figure_1](https://user-images.githubusercontent.com/3699983/80449079-0b764a00-88d3-11ea-8bf7-a5030255513b.png)

Will update README.md to reflect this

**Comment by VolkerH** [comment]
Just saw these recently added notebooks.
These are a great resource, thank you !
